version: '3'
services:
    db:
        image: postgres:10
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        volumes:
            - ./tmp/db:/var/lib/postgresql/data
    ret:
        build: .
        environment:
            - "DB_HOST=db"
        command: bash -c "source ~/.bashrc; pushd assets; yarn; popd; mix local.hex --force; mix local.rebar --force; mix phx.server"
        volumes:
            - .:/ret
        ports:
            - "4000:4000"
        depends_on:
            - db
